# ── BASEMAP ──────────────────────────────────────────────
ONEMAP_BASEMAP = "https://www.onemap.gov.sg/maps/json/raster/mbstyle/Default.json"

# ── MASTER PLAN LAND USE COLOURS (official URA scheme) ───
LAND_USE_COLORS = {
    "RESIDENTIAL":                               [255, 218, 185, 180],
    "RESIDENTIAL WITH COMMERCIAL AT 1ST STOREY": [255, 200, 150, 180],
    "COMMERCIAL":                                [255, 0,   0,   180],
    "COMMERCIAL & RESIDENTIAL":                  [255, 160, 122, 180],
    "HOTEL":                                     [255, 105, 180, 180],
    "WHITE":                                     [255, 255, 255, 200],
    "BUSINESS 1":                                [153, 153, 255, 180],
    "BUSINESS 1 - WHITE":                        [180, 153, 255, 180],
    "BUSINESS 2":                                [102, 102, 204, 180],
    "BUSINESS 2 - WHITE":                        [130, 102, 204, 180],
    "BUSINESS PARK":                             [204, 153, 255, 180],
    "BUSINESS PARK - WHITE":                     [220, 180, 255, 180],
    "OPEN SPACE":                                [0,   180, 0,   180],
    "PARK":                                      [0,   153, 0,   180],
    "NATURE RESERVE":                            [0,   102, 0,   180],
    "BEACH AREA":                                [135, 206, 235, 180],
    "WATERBODY":                                 [0,   150, 255, 180],
    "TRANSPORT":                                 [200, 200, 200, 180],
    "ROAD":                                      [220, 220, 220, 180],
    "MASS RAPID TRANSIT":                        [160, 160, 160, 180],
    "CIVIC & COMMUNITY":                         [0,   220, 220, 180],
    "EDUCATIONAL INSTITUTION":                   [0,   191, 255, 180],
    "HEALTH & MEDICAL CARE":                     [255, 0,   128, 180],
    "PLACE OF WORSHIP":                          [210, 180, 140, 180],
    "COMMUNITY INSTITUTION":                     [100, 220, 220, 180],
    "UTILITY":                                   [255, 255, 0,   180],
    "SPECIAL USE":                               [200, 180, 160, 180],
    "RESERVE SITE":                              [211, 211, 211, 180],
    "CEMETERY":                                  [180, 180, 180, 180],
    "PORT / AIRPORT":                            [160, 160, 160, 180],
    "AGRICULTURE":                               [144, 238, 144, 180],
}
DEFAULT_MP_COLOR = [220, 220, 220, 120]

# ── AMENITY CATEGORY COLOURS ─────────────────────────────
AMENITY_CATEGORY_COLORS = {
    "Community":              [204, 153, 0,   240],
    "Culture":                [102, 0,   204, 240],
    "Education":              [0,   153, 0,   240],
    "Emergency Preparedness": [255, 50,  50,  240],
    "Employment":             [0,   180, 180, 240],
    "Environment":            [0,   153, 0,   240],
    "Family":                 [255, 180, 0,   240],
    "Government Offices":     [150, 150, 150, 240],
    "Health":                 [204, 0,   0,   240],
    "National Service":       [100, 100, 200, 240],
    "Recreation":             [0,   180, 60,  240],
    "Sports":                 [0,   120, 255, 240],
    "Other":                  [180, 180, 180, 240],
}

MRT_COLOR = [0, 102, 204, 240]

# ── DATA SOURCES SUMMARY ─────────────────────────────────
DATA_SOURCES = [
    {"Layer": "Transactions",   "Source": "URA Data Service",  "Updated": "Tue & Fri"},
    {"Layer": "GLS Sites",      "Source": "data.gov.sg (URA)", "Updated": "Dec 2025"},
    {"Layer": "Master Plan",    "Source": "data.gov.sg (URA)", "Updated": "Dec 2025"},
    {"Layer": "MRT Stations",   "Source": "data.gov.sg (LTA)", "Updated": "Ongoing"},
    {"Layer": "Amenities",      "Source": "OneMap Themes",     "Updated": "Various"},
]

# ── MRT LINE COLOURS ─────────────────────────────────────
# Official Singapore MRT line colours (RGB)
MRT_LINE_COLORS = {
    "NS": [220, 28,  35,  240],   # Red
    "EW": [0,   155, 68,  240],   # Green
    "CG": [0,   155, 68,  240],   # Green (Changi branch of EW)
    "NE": [142, 36,  170, 240],   # Purple
    "CC": [255, 163, 0,   240],   # Orange/Yellow
    "CE": [255, 163, 0,   240],   # Orange (Circle extension)
    "DT": [0,   93,  168, 240],   # Blue
    "TE": [121, 68,  47,  240],   # Brown
    "BP": [116, 179, 224, 240],   # Light Blue (Bukit Panjang LRT)
    "SK": [116, 179, 224, 240],   # Light Blue (Sengkang LRT)
    "PG": [116, 179, 224, 240],   # Light Blue (Punggol LRT)
    "JS": [0,   178, 169, 240],   # Teal (Jurong Region)
    "JE": [0,   178, 169, 240],   # Teal
    "JW": [0,   178, 169, 240],   # Teal
    "CR": [0,   168, 107, 240],   # Green (Cross Island)
    "CP": [0,   168, 107, 240],   # Green (Cross Island branch)
}

MRT_DEFAULT_COLOR = [80, 80, 80, 240]

# Station name → line codes mapping (for interchange display)
# Format: "STATION NAME": ["LINE1", "LINE2", ...]
MRT_STATION_LINES = {
    "JURONG EAST": ["NS", "EW"],
    "BUONA VISTA": ["EW", "CC"],
    "CITY HALL": ["NS", "EW"],
    "RAFFLES PLACE": ["NS", "EW"],
    "OUTRAM PARK": ["EW", "NE", "TE"],
    "DHOBY GHAUT": ["NS", "NE", "CC"],
    "MARINA BAY": ["NS", "CE", "TE"],
    "PAYA LEBAR": ["EW", "CC"],
    "BISHAN": ["NS", "CC"],
    "NEWTON": ["NS", "DT"],
    "ORCHARD": ["NS", "TE"],
    "BUGIS": ["EW", "DT"],
    "BRAS BASAH": ["CC"],
    "ESPLANADE": ["CC"],
    "PROMENADE": ["CC", "DT"],
    "BAYFRONT": ["CC", "DT"],
    "HARBOURFRONT": ["NE", "CC"],
    "ONE NORTH": ["CC"],
    "KENT RIDGE": ["CC"],
    "HEX": ["CC"],
    "BUKIT PANJANG": ["DT", "BP"],
    "CHOA CHU KANG": ["NS", "BP", "JS"],
    "SERANGOON": ["NE", "CC"],
    "LORONG CHUAN": ["CC"],
    "PUNGGOL": ["NE", "PG"],
    "SENGKANG": ["NE", "SK"],
    "WOODLANDS": ["NS", "TE"],
    "CALDECOTT": ["CC", "TE"],
    "STEVENS": ["DT", "TE"],
    "BRIGHT HILL": ["CR", "TE"],
    "ANG MO KIO": ["NS", "CR"],
    "HOUGANG": ["NE", "CR"],
    "PASIR RIS": ["EW", "CR", "CP"],
    "EXPO": ["EW", "DT"],
    "TANAH MERAH": ["EW"],
    "CHANGI AIRPORT": ["CG"],
    "BOON LAY": ["EW", "JS"],
    "BAYSHORE": ["TE"],
    "SUNGEI BEDOK": ["TE", "DT"],
    "TANJONG PAGAR": ["EW"],
    "TIONG BAHRU": ["EW"],
    "REDHILL": ["EW"],
    "QUEENSTOWN": ["EW"],
    "COMMONWEALTH": ["EW"],
    "DOVER": ["EW"],
    "CLEMENTI": ["EW"],
    "CHINESE GARDEN": ["EW"],
    "LAKESIDE": ["EW"],
    "PIONEER": ["EW"],
    "JOO KOON": ["EW"],
    "GUL CIRCLE": ["EW"],
    "TUAS CRESCENT": ["EW"],
    "TUAS WEST ROAD": ["EW"],
    "TUAS LINK": ["EW"],
    "ALJUNIED": ["EW"],
    "KALLANG": ["EW"],
    "LAVENDER": ["EW"],
    "EUNOS": ["EW"],
    "KEMBANGAN": ["EW"],
    "BEDOK": ["EW"],
    "SIMEI": ["EW"],
    "TAMPINES": ["EW", "DT"],
    "PASIR RIS EAST": ["CR"],
    "MARINA SOUTH PIER": ["NS"],
    "CANBERRA": ["NS"],
    "SEMBAWANG": ["NS"],
    "ADMIRALTY": ["NS"],
    "YISHUN": ["NS"],
    "KHATIB": ["NS"],
    "YIO CHU KANG": ["NS"],
    "BRADDELL": ["NS"],
    "TOA PAYOH": ["NS"],
    "NOVENA": ["NS"],
    "SOMERSET": ["NS"],
    "BUKIT BATOK": ["NS"],
    "BUKIT GOMBAK": ["NS"],
    "YEW TEE": ["NS"],
    "KRANJI": ["NS"],
    "MARSILING": ["NS"],
    "WOODLANDS SOUTH": ["TE"],
    "WOODLANDS NORTH": ["TE"],
    "SPRINGLEAF": ["TE"],
    "LENTOR": ["TE"],
    "MAYFLOWER": ["TE"],
    "UPPER THOMSON": ["TE"],
    "MOUNT PLEASANT": ["TE"],
    "ORCHARD BOULEVARD": ["TE"],
    "NAPIER": ["TE"],
    "GREAT WORLD": ["TE"],
    "HAVELOCK": ["TE"],
    "MAXWELL": ["TE"],
    "SHENTON WAY": ["TE"],
    "MARINA SOUTH": ["TE"],
    "GARDENS BY THE BAY": ["TE"],
    "TANJONG RHU": ["TE"],
    "KATONG PARK": ["TE"],
    "TANJONG KATONG": ["TE"],
    "MARINE PARADE": ["TE"],
    "MARINE TERRACE": ["TE"],
    "SIGLAP": ["TE"],
    "BEDOK SOUTH": ["TE"],
    "HARBOURFRONT": ["NE", "CC"],
    "CHINATOWN": ["NE", "DT"],
    "CLARKE QUAY": ["NE"],
    "LITTLE INDIA": ["NE", "DT"],
    "FARRER PARK": ["NE"],
    "BOON KENG": ["NE"],
    "POTONG PASIR": ["NE"],
    "WOODLEIGH": ["NE"],
    "KOVAN": ["NE"],
    "BUANGKOK": ["NE"],
    "RIVIERA": ["PG"],
    "HUME": ["DT"],
    "BEAUTY WORLD": ["DT"],
    "KING ALBERT PARK": ["DT"],
    "SIXTH AVENUE": ["DT"],
    "TAN KAH KEE": ["DT"],
    "BOTANIC GARDENS": ["CC", "DT"],
    "FARRER ROAD": ["CC"],
    "HOLLAND VILLAGE": ["CC"],
    "BUONA VISTA": ["EW", "CC"],
    "ONE-NORTH": ["CC"],
    "KENT RIDGE": ["CC"],
    "HAW PAR VILLA": ["CC"],
    "PASIR PANJANG": ["CC"],
    "LABRADOR PARK": ["CC"],
    "TELOK BLANGAH": ["CC"],
    "KEPPEL": ["CC"],
    "CANTONMENT": ["CC"],
    "PRINCE EDWARD ROAD": ["CC"],
    "ROCHOR": ["DT"],
    "BENCOOLEN": ["DT"],
    "JALAN BESAR": ["DT"],
    "BENDEMEER": ["DT"],
    "GEYLANG BAHRU": ["DT"],
    "MATTAR": ["DT"],
    "UBI": ["DT"],
    "KAKI BUKIT": ["DT"],
    "BEDOK NORTH": ["DT"],
    "BEDOK RESERVOIR": ["DT"],
    "TAMPINES WEST": ["DT"],
    "TAMPINES EAST": ["DT"],
    "UPPER CHANGI": ["DT"],
    "XILIN": ["DT"],
    "SUNGEI BEDOK": ["DT", "TE"],
    "FORT CANNING": ["DT"],
    "CHINATOWN": ["NE", "DT"],
    "TELOK AYER": ["DT"],
    "DOWNTOWN": ["DT"],
    "SHENTON WAY": ["TE"],
    "TECK GHEE": ["CR"],
    "SERANGOON NORTH": ["CR"],
    "TAVISTOCK": ["CR"],
    "DEFU": ["CR"],
    "TAMPINES NORTH": ["CR"],
    "LOYANG": ["CR"],
    "AVIATION PARK": ["CR"],
    "ELIAS": ["CP"],
    "CHOA CHU KANG WEST": ["JS"],
    "TENGAH": ["JS"],
    "HONG KAH": ["JS"],
    "ENTERPRISE": ["JS"],
    "TAWAS": ["JS"],
    "BAHAR JUNCTION": ["JS"],
    "JURONG PIER": ["JS"],
    "PANDAN RESERVOIR": ["JE"],
    "WEST COAST": ["JW"],
    "PENG KANG HILL": ["JW"],
    "MAJU":           ["BP"],
    "SEGAR":          ["BP"],
    "JELAPANG":       ["BP"],
    "SENJA":          ["BP"],
    "PHOENIX":        ["BP"],
    "PENDING":        ["BP"],
    "BANGKIT":        ["BP"],
    "FAJAR":          ["BP"],
    "RANGGUNG":       ["SK"],
    "CHENG LIM":      ["SK"],
    "FARMWAY":        ["SK"],
    "KUPANG":         ["SK"],
    "THANGGAM":       ["SK"],
    "FERNVALE":       ["SK"],
    "LAYAR":          ["SK"],
    "TONGKANG":       ["SK"],
    "RENJONG":        ["SK"],
    "COMPASSVALE":    ["SK"],
    "RUMBIA":         ["SK"],
    "BAKAU":          ["SK"],
    "KANGKAR":        ["SK"],
    "MERIDIAN":       ["PG"],
    "CORAL EDGE":     ["PG"],
    "KADALOOR":       ["PG"],
    "OASIS":          ["PG"],
    "DAMAI":          ["PG"],
    "SAM KEE":        ["PG"],
    "TECK LEE":       ["PG"],
    "PUNGGOL POINT":  ["PG"],
    "SAMUDERA":       ["PG"],
    "NIBONG":         ["PG"],
    "SUMANG":         ["PG"],
    "SOO TECK":       ["PG"],
}
